### ISSUE TITLE
ArbitraryPlanarRectangularXSCircuit edge case anomaly on TF

### ISSUE THREAD

**Issue by s-aria** [Fusion-Power-Plant-Framework/bluemira#723] opened 2022-02-16 12:13 UTC
When using ArbitraryPlanarRectangularXSCircuit(leg_conductor, TF.params.tf_wp_width / 2, TF.params.tf_wp_depth / 2, current), it will fail to create the appropriate rectangle in the TF coil. 

```
tf_wp_width_2 = 0.76
tf_wp_depth_2 = 0.3661766590123879
current = 3487374.9999999995
leg_conductor_array = np.array([[  0.80204   ,   1.17761349,   1.55589661,   1.93418151,
          2.30514822,   2.64570018,   2.99188707,   3.3455652 ,
          3.70602578,   4.07203239,   4.44256948,   4.81669731,
          5.19321567,   5.57112983,   5.94933131,   6.32678415,
          6.70232415,   7.07497664,   7.44366521,   7.8072364 ,
          8.16487232,   8.51527801,   8.85761204,   9.18082796,
          9.33491024,   9.3645278 ,   9.36644188,   9.36649742,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649803,
          9.36649656,   9.36639084,   9.36323572,   9.32966755,
          9.16946709,   8.8581428 ,   8.5157768 ,   8.16532791,
          7.80793393,   7.4442285 ,   7.07561783,   6.70298324,
          6.32739726,   5.94999021,   5.57177671,   5.19386971,
          4.81730881,   4.44325379,   4.07263427,   3.70663567,
          3.34624876,   2.99235125,   2.64635473,   2.30584435,
          1.93490956,   1.55662724,   1.17834578,   0.80204   ],
       [-10.00776431, -10.03912246, -10.03987644, -10.04008266,
        -10.09392677, -10.25854168, -10.41090188, -10.54496309,
        -10.65955591, -10.7549295 , -10.8308612 , -10.88644827,
        -10.92239766, -10.93801717, -10.93339927, -10.90904513,
        -10.86394065, -10.79923117, -10.71477997, -10.61049478,
        -10.48738026, -10.344972  , -10.18414948,  -9.98964832,
         -9.65074586,  -9.27420763,  -8.89593092,  -8.51764582,
         -8.1393607 ,  -7.76107558,  -7.38279046,  -7.00450535,
         -6.62622023,  -6.24793511,  -5.86964999,  -5.49136487,
         -5.11307976,  -4.73479464,  -4.35650952,  -3.9782244 ,
         -3.59993929,  -3.22165417,  -2.84336905,  -2.46508393,
         -2.08679881,  -1.7085137 ,  -1.33022858,  -0.95194346,
         -0.57365834,  -0.19537323,   0.18291189,   0.56119701,
          0.93948213,   1.31776725,   1.69605236,   2.07433748,
          2.4526226 ,   2.83090772,   3.20919284,   3.58747795,
          3.96576307,   4.34404819,   4.72233331,   5.10061842,
          5.47890354,   5.85718866,   6.23547378,   6.6137589 ,
          6.99204401,   7.37032913,   7.74861425,   8.12689937,
          8.50518448,   8.88346957,   9.26172885,   9.63803793,
          9.97505383,  10.18394008,  10.34471778,  10.48699567,
         10.61082976,  10.71467296,  10.79942949,  10.86429509,
         10.90894948,  10.93396499,  10.9382766 ,  10.92267551,
         10.8870935 ,  10.8310223 ,  10.75552167,  10.66008389,
         10.54528528,  10.41178912,  10.25897969,  10.09468637,
         10.04037353,  10.0398684 ,  10.03887109,  10.00855903]])
```

![image](https://user-images.githubusercontent.com/74428421/154262108-ecdbaf93-c6d8-4925-87d4-b33c371edf4b.png)

**Comment by CoronelBuendia** [comment] 2022-02-16 12:31
I can confirm (sadly) that is not just a plotting issue

```python
import matplotlib.pyplot as plt
import numpy as np

from bluemira.geometry.coordinates import Coordinates
from bluemira.magnetostatics.circuits import ArbitraryPlanarRectangularXSCircuit


tf_wp_width_2 = 0.76
tf_wp_depth_2 = 0.3661766590123879
current = 3487374.9999999995
leg_conductor_array = np.array([[  0.80204   ,   1.17761349,   1.55589661,   1.93418151,
          2.30514822,   2.64570018,   2.99188707,   3.3455652 ,
          3.70602578,   4.07203239,   4.44256948,   4.81669731,
          5.19321567,   5.57112983,   5.94933131,   6.32678415,
          6.70232415,   7.07497664,   7.44366521,   7.8072364 ,
          8.16487232,   8.51527801,   8.85761204,   9.18082796,
          9.33491024,   9.3645278 ,   9.36644188,   9.36649742,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649805,
          9.36649805,   9.36649805,   9.36649805,   9.36649803,
          9.36649656,   9.36639084,   9.36323572,   9.32966755,
          9.16946709,   8.8581428 ,   8.5157768 ,   8.16532791,
          7.80793393,   7.4442285 ,   7.07561783,   6.70298324,
          6.32739726,   5.94999021,   5.57177671,   5.19386971,
          4.81730881,   4.44325379,   4.07263427,   3.70663567,
          3.34624876,   2.99235125,   2.64635473,   2.30584435,
          1.93490956,   1.55662724,   1.17834578,   0.80204   ],
       [-10.00776431, -10.03912246, -10.03987644, -10.04008266,
        -10.09392677, -10.25854168, -10.41090188, -10.54496309,
        -10.65955591, -10.7549295 , -10.8308612 , -10.88644827,
        -10.92239766, -10.93801717, -10.93339927, -10.90904513,
        -10.86394065, -10.79923117, -10.71477997, -10.61049478,
        -10.48738026, -10.344972  , -10.18414948,  -9.98964832,
         -9.65074586,  -9.27420763,  -8.89593092,  -8.51764582,
         -8.1393607 ,  -7.76107558,  -7.38279046,  -7.00450535,
         -6.62622023,  -6.24793511,  -5.86964999,  -5.49136487,
         -5.11307976,  -4.73479464,  -4.35650952,  -3.9782244 ,
         -3.59993929,  -3.22165417,  -2.84336905,  -2.46508393,
         -2.08679881,  -1.7085137 ,  -1.33022858,  -0.95194346,
         -0.57365834,  -0.19537323,   0.18291189,   0.56119701,
          0.93948213,   1.31776725,   1.69605236,   2.07433748,
          2.4526226 ,   2.83090772,   3.20919284,   3.58747795,
          3.96576307,   4.34404819,   4.72233331,   5.10061842,
          5.47890354,   5.85718866,   6.23547378,   6.6137589 ,
          6.99204401,   7.37032913,   7.74861425,   8.12689937,
          8.50518448,   8.88346957,   9.26172885,   9.63803793,
          9.97505383,  10.18394008,  10.34471778,  10.48699567,
         10.61082976,  10.71467296,  10.79942949,  10.86429509,
         10.90894948,  10.93396499,  10.9382766 ,  10.92267551,
         10.8870935 ,  10.8310223 ,  10.75552167,  10.66008389,
         10.54528528,  10.41178912,  10.25897969,  10.09468637,
         10.04037353,  10.0398684 ,  10.03887109,  10.00855903]])

leg = Coordinates({"x": leg_conductor_array[0], "y": 0, "z":leg_conductor_array[1]})
circuit = ArbitraryPlanarRectangularXSCircuit(leg, tf_wp_width_2, tf_wp_depth_2, current)

n = 100
x = np.linspace(0, 10, n)
z = np.linspace(-12, 12, n)

xx, zz = np.meshgrid(x, z)
yy = np.zeros((n, n))

B = circuit.field(xx, yy, zz)

f, ax = plt.subplots()
ax.plot(leg.x, leg.z)
ax.contourf(xx, zz, B[1])
ax.set_aspect("equal")
```

![image](https://user-images.githubusercontent.com/26097289/154265004-1bacc67e-9d93-401c-b81d-5ad51557ec03.png)

**Comment by CoronelBuendia** [comment] 2022-02-16 12:54
It's partly a discretisation issue: if you reduce the width of the cross-section by an OOM, this mostly goes away, but there is still some funniness at the end points.

Basically the trapezoids overlap because the XS is larger than the discretisation size and in places you get doubled sources.

![image](https://user-images.githubusercontent.com/26097289/154268655-0c7050d7-e0e3-43e6-ad72-4e35dd658b82.png)

I will look into it

**Comment by CoronelBuendia** [comment] 2022-02-18 10:52
OK, definitely making some progress:
![image](https://user-images.githubusercontent.com/26097289/154669098-c233c9af-7dbb-4204-b161-736b597cfea8.png)

Just need to catch the change in curvature direction now..

**Comment by je-cook** [comment] 2022-02-18 12:51
At least this is a horrible test for it!

**Comment by CoronelBuendia** [comment] 2022-02-18 14:24
So this thing was implicitly expecting shapes with a constant direction of curvature... I'm battling away and can it to do things like this:
![image](https://user-images.githubusercontent.com/26097289/154700399-53727666-645a-42b6-b27f-2b41b1e33bdd.png)

but I still can't get the original shape to work. @s-aria might need to ping  you

**Comment by s-aria** [comment] 2022-02-20 21:13
> So this thing was implicitly expecting shapes with a constant direction of curvature... I'm battling away and can it to do things like this: ![image](https://user-images.githubusercontent.com/26097289/154700399-53727666-645a-42b6-b27f-2b41b1e33bdd.png)
> 
> but I still can't get the original shape to work. @s-aria might need to ping you

I could definitely give it a go. Is this the contour plot of the field lines? The other image seems to be great progress already tho. I could give it a go and see how close we are compared to the same FEA model?

**Comment by CoronelBuendia** [comment] 2022-02-21 06:40
Yeah I should hopefully get this wrapped up today. Note that I still expect there to be issues related to discretisation (if you over-discretise relative to the cross-section size, you run the risk of overlaps between the individual current sources).

**Comment by CoronelBuendia** [comment] 2022-02-21 07:19
OK, so I think I'm getting there:

![image](https://user-images.githubusercontent.com/26097289/154906755-073b580f-2869-44fb-95a3-4a8bcbd4b7f9.png)

Toroidal field 200 x 200:
![image](https://user-images.githubusercontent.com/26097289/154906812-0f51853a-d887-4961-9716-c49c6bae6a84.png)

I'll put in a PR, but would greatly appreciate some benchmark with an FEA model on a single funky coil shape like this one (i.e. not a full TF coil set.

**Comment by CoronelBuendia** [comment] 2022-02-21 07:36
There is still an issue when a single element sees both directions of curvature strongly..

n = 150 (first 30 shown):
![image](https://user-images.githubusercontent.com/26097289/154908957-a54140d6-c7fb-4b43-b6bd-86eadd5f2044.png)

n = 100 (first 30 shown):
![image](https://user-images.githubusercontent.com/26097289/154909051-fa75b194-4a16-46a7-97a6-43bde466c0e2.png)

Honestly, not sure if this is really worth catching: this is not the recommended way for treating circular arcs, and can be resolved by "better" discretisation.

**Comment by CoronelBuendia** [comment] 2022-03-10 08:13
not sure how this happened, but things look worse now with this bloody thing. I'm working on adding proper tests this time and fixing this thing once and for all...

**Closed** 2022-03-29 11:00 UTC
Labels: bug, magnetostatics, tf_coil, display
